# Generated by Django 5.2.7 on 2025-10-08 07:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Well",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("well_name", models.CharField(max_length=255, unique=True)),
                (
                    "well_type",
                    models.CharField(
                        choices=[
                            ("Oil", "Oil"),
                            ("Gas", "Gas"),
                            ("Water", "Water"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Well",
                "verbose_name_plural": "Wells",
                "db_table": "wells",
            },
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("run_number", models.CharField(max_length=100, unique=True)),
                ("run_name", models.CharField(max_length=255, unique=True)),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("GTL", "GTL"),
                            ("Gyro", "Gyro"),
                            ("MWD", "MWD"),
                            ("Unknown", "Unknown"),
                        ],
                        max_length=50,
                    ),
                ),
                ("vertical_section", models.JSONField(blank=True, null=True)),
                ("bhc_enabled", models.BooleanField(default=False)),
                (
                    "proposal_direction",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "grid_correction",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="survey_api.well",
                    ),
                ),
            ],
            options={
                "verbose_name": "Run",
                "verbose_name_plural": "Runs",
                "db_table": "runs",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=11)),
                (
                    "easting",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "northing",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "geodetic_system",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("map_zone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "north_reference",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "central_meridian",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location",
                        to="survey_api.run",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "db_table": "locations",
            },
        ),
        migrations.CreateModel(
            name="Depth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "elevation_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reference_datum",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reference_height",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "reference_elevation",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depth",
                        to="survey_api.run",
                    ),
                ),
            ],
            options={
                "verbose_name": "Depth",
                "verbose_name_plural": "Depths",
                "db_table": "depths",
            },
        ),
        migrations.CreateModel(
            name="SurveyFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.BigIntegerField()),
                (
                    "survey_type",
                    models.CharField(
                        choices=[
                            ("GTL", "GTL"),
                            ("Gyro", "Gyro"),
                            ("MWD", "MWD"),
                            ("Unknown", "Unknown"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=50,
                    ),
                ),
                ("calculated_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_files",
                        to="survey_api.run",
                    ),
                ),
            ],
            options={
                "verbose_name": "Survey File",
                "verbose_name_plural": "Survey Files",
                "db_table": "survey_files",
            },
        ),
        migrations.CreateModel(
            name="SurveyCalculation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("calculation_type", models.CharField(max_length=100)),
                ("parameters", models.JSONField(blank=True, null=True)),
                ("results", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="processing",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "survey_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculations",
                        to="survey_api.surveyfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Survey Calculation",
                "verbose_name_plural": "Survey Calculations",
                "db_table": "survey_calculations",
            },
        ),
        migrations.AddIndex(
            model_name="surveyfile",
            index=models.Index(fields=["run"], name="idx_survey_files_run_id"),
        ),
        migrations.AddIndex(
            model_name="surveyfile",
            index=models.Index(
                fields=["processing_status"], name="idx_survey_files_status"
            ),
        ),
        migrations.AddIndex(
            model_name="surveycalculation",
            index=models.Index(fields=["survey_file"], name="idx_survey_calc_file_id"),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["well"], name="idx_runs_well_id"),
        ),
    ]
