# Generated by Django 5.2.7 on 2025-10-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "survey_api",
            "0002_well_run_location_depth_surveyfile_surveycalculation_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="run",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
