# Generated by Django 5.2.7 on 2025-10-12 10:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0004_alter_location_options_location_g_t_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="depth",
            options={},
        ),
        migrations.AddField(
            model_name="depth",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="depth",
            name="well",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="depth",
                to="survey_api.well",
            ),
        ),
        migrations.AlterField(
            model_name="depth",
            name="elevation_reference",
            field=models.CharField(
                choices=[
                    ("KB", "Kelly Bushing"),
                    ("RT", "Rotary Table"),
                    ("GL", "Ground Level"),
                    ("MSL", "Mean Sea Level"),
                    ("DF", "Derrick Floor"),
                    ("RKB", "Rotary Kelly Bushing"),
                ],
                default="KB",
                help_text="Elevation reference point (KB, RT, GL, MSL, etc.)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="depth",
            name="reference_datum",
            field=models.CharField(
                default="WGS84",
                help_text="Reference datum (e.g., WGS84, NAVD88)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="depth",
            name="reference_elevation",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                help_text="Reference elevation in feet or meters",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="depth",
            name="reference_height",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                help_text="Reference height in feet or meters",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="depth",
            name="run",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="depth",
                to="survey_api.run",
            ),
        ),
        migrations.AddIndex(
            model_name="depth",
            index=models.Index(fields=["run"], name="idx_depths_run_id"),
        ),
        migrations.AddIndex(
            model_name="depth",
            index=models.Index(fields=["well"], name="idx_depths_well_id"),
        ),
        migrations.AddConstraint(
            model_name="depth",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("run__isnull", False), ("well__isnull", True)),
                    models.Q(("run__isnull", True), ("well__isnull", False)),
                    _connector="OR",
                ),
                name="depth_run_or_well_check",
            ),
        ),
    ]
