# Generated by Django 5.2.7 on 2025-10-12 11:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0005_alter_depth_options_depth_updated_at_depth_well_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "survey_type",
                    models.CharField(
                        choices=[
                            ("Type 1 - GTL", "Type 1 - GTL"),
                            ("Type 2 - Gyro", "Type 2 - Gyro"),
                            ("Type 3 - MWD", "Type 3 - MWD"),
                            ("Type 4 - Unknown", "Type 4 - Unknown"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("uploaded", "Uploaded"),
                            ("validated", "Validated"),
                            ("calculated", "Calculated"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey",
                        to="survey_api.run",
                    ),
                ),
            ],
            options={
                "db_table": "surveys",
                "indexes": [
                    models.Index(fields=["run"], name="idx_surveys_run_id"),
                    models.Index(
                        fields=["survey_type"], name="idx_surveys_survey_type"
                    ),
                    models.Index(fields=["status"], name="idx_surveys_status"),
                ],
            },
        ),
    ]
