# Generated by Django 5.2.7 on 2025-10-12 17:37

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0006_survey"),
    ]

    operations = [
        migrations.CreateModel(
            name="TieOn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "md",
                    models.DecimalField(
                        decimal_places=3, help_text="Measured Depth", max_digits=10
                    ),
                ),
                (
                    "inc",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Inclination (0-180 degrees)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("180.00")),
                        ],
                    ),
                ),
                (
                    "azi",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Azimuth (0-360 degrees)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("360.00")),
                        ],
                    ),
                ),
                (
                    "tvd",
                    models.DecimalField(
                        decimal_places=3, help_text="True Vertical Depth", max_digits=10
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Latitude coordinate (+N/-S)",
                        max_digits=12,
                    ),
                ),
                (
                    "departure",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Departure coordinate (+E/-W)",
                        max_digits=12,
                    ),
                ),
                (
                    "well_type",
                    models.CharField(help_text="Type of well", max_length=100),
                ),
                (
                    "hole_section",
                    models.CharField(
                        choices=[
                            ("Surface Casing", "Surface Casing"),
                            ("Intermediate Casing", "Intermediate Casing"),
                            ("Production Casing", "Production Casing"),
                            ("Liner", "Liner"),
                            ("Open Hole", "Open Hole"),
                        ],
                        help_text="Hole section type",
                        max_length=100,
                    ),
                ),
                (
                    "casing_selected",
                    models.BooleanField(
                        default=False, help_text="Casing checkbox selection"
                    ),
                ),
                (
                    "drillpipe_selected",
                    models.BooleanField(
                        default=False, help_text="Drillpipe checkbox selection"
                    ),
                ),
                (
                    "survey_tool_type",
                    models.CharField(
                        choices=[
                            ("MWD", "MWD"),
                            ("LWD", "LWD"),
                            ("Wireline Gyro", "Wireline Gyro"),
                            ("Steering Tool", "Steering Tool"),
                            ("Other", "Other"),
                        ],
                        help_text="Survey tool type",
                        max_length=100,
                    ),
                ),
                (
                    "survey_interval_from",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Survey interval from depth",
                        max_digits=10,
                    ),
                ),
                (
                    "survey_interval_to",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Survey interval to depth",
                        max_digits=10,
                    ),
                ),
                (
                    "survey_interval_length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Auto-calculated survey interval length (to - from)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tieon",
                        to="survey_api.run",
                    ),
                ),
            ],
            options={
                "db_table": "tieons",
                "indexes": [models.Index(fields=["run"], name="idx_tieons_run_id")],
            },
        ),
    ]
