# Generated by Django 5.2.7 on 2025-10-13 19:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0007_tieon"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("md_data", models.JSONField(help_text="Measured Depth array")),
                ("inc_data", models.JSONField(help_text="Inclination array (degrees)")),
                ("azi_data", models.JSONField(help_text="Azimuth array (degrees)")),
                (
                    "wt_data",
                    models.JSONField(
                        blank=True, help_text="w(t) for GTL surveys", null=True
                    ),
                ),
                (
                    "gt_data",
                    models.JSONField(
                        blank=True, help_text="g(t) for GTL surveys", null=True
                    ),
                ),
                (
                    "row_count",
                    models.IntegerField(help_text="Number of survey stations"),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "validation_errors",
                    models.JSONField(
                        blank=True,
                        help_text="Array of validation error messages",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "survey_file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_data",
                        to="survey_api.surveyfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Survey Data",
                "verbose_name_plural": "Survey Data",
                "db_table": "survey_data",
                "indexes": [
                    models.Index(
                        fields=["survey_file"], name="idx_survey_data_file_id"
                    ),
                    models.Index(
                        fields=["validation_status"], name="idx_survey_data_validation"
                    ),
                ],
            },
        ),
    ]
