# Generated by Django 5.1.5 on 2025-10-14 07:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0008_surveydata"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalculatedSurvey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "easting",
                    models.JSONField(help_text="X coordinate / Easting (meters)"),
                ),
                (
                    "northing",
                    models.JSONField(help_text="Y coordinate / Northing (meters)"),
                ),
                ("tvd", models.JSONField(help_text="True Vertical Depth (meters)")),
                (
                    "dls",
                    models.JSONField(
                        blank=True,
                        help_text="Dog Leg Severity (degrees/30m)",
                        null=True,
                    ),
                ),
                (
                    "build_rate",
                    models.JSONField(
                        blank=True, help_text="Build Rate (degrees/30m)", null=True
                    ),
                ),
                (
                    "turn_rate",
                    models.JSONField(
                        blank=True, help_text="Turn Rate (degrees/30m)", null=True
                    ),
                ),
                (
                    "calculation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("calculated", "Calculated"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        help_text="Current status of calculation",
                        max_length=50,
                    ),
                ),
                (
                    "calculation_duration",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Calculation time in seconds",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if calculation failed",
                        null=True,
                    ),
                ),
                (
                    "calculation_context",
                    models.JSONField(
                        help_text="Location, Depth, TieOn data used for calculation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "survey_data",
                    models.OneToOneField(
                        help_text="Link to source survey data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculated_survey",
                        to="survey_api.surveydata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calculated Survey",
                "verbose_name_plural": "Calculated Surveys",
                "db_table": "calculated_surveys",
                "indexes": [
                    models.Index(
                        fields=["survey_data"], name="idx_calc_survey_data_id"
                    ),
                    models.Index(
                        fields=["calculation_status"], name="idx_calc_survey_status"
                    ),
                ],
            },
        ),
    ]
