# Generated by Django 5.1.5 on 2025-10-14 08:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0009_calculatedsurvey"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterpolatedSurvey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "resolution",
                    models.IntegerField(
                        help_text="Interpolation resolution (spacing between points in meters)"
                    ),
                ),
                (
                    "md_interpolated",
                    models.JSONField(help_text="Interpolated Measured Depth (meters)"),
                ),
                (
                    "inc_interpolated",
                    models.JSONField(help_text="Interpolated Inclination (degrees)"),
                ),
                (
                    "azi_interpolated",
                    models.JSONField(help_text="Interpolated Azimuth (degrees)"),
                ),
                (
                    "easting_interpolated",
                    models.JSONField(
                        help_text="Interpolated Easting / X coordinate (meters)"
                    ),
                ),
                (
                    "northing_interpolated",
                    models.JSONField(
                        help_text="Interpolated Northing / Y coordinate (meters)"
                    ),
                ),
                (
                    "tvd_interpolated",
                    models.JSONField(
                        help_text="Interpolated True Vertical Depth (meters)"
                    ),
                ),
                (
                    "dls_interpolated",
                    models.JSONField(
                        help_text="Interpolated Dog Leg Severity (degrees/30m)"
                    ),
                ),
                (
                    "interpolation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        help_text="Current interpolation status",
                        max_length=50,
                    ),
                ),
                (
                    "point_count",
                    models.IntegerField(
                        help_text="Number of interpolated points generated"
                    ),
                ),
                (
                    "interpolation_duration",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Interpolation processing time in seconds",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if interpolation failed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "calculated_survey",
                    models.ForeignKey(
                        help_text="Parent calculated survey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interpolations",
                        to="survey_api.calculatedsurvey",
                    ),
                ),
            ],
            options={
                "db_table": "interpolated_surveys",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["calculated_survey"], name="idx_interp_survey_calc_id"
                    ),
                    models.Index(
                        fields=["resolution"], name="idx_interp_survey_resolution"
                    ),
                    models.Index(
                        fields=["interpolation_status"], name="idx_interp_survey_status"
                    ),
                ],
                "unique_together": {("calculated_survey", "resolution")},
            },
        ),
    ]
