# Generated by Django 5.2.7 on 2025-10-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0010_interpolatedsurvey"),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedsurvey',
            name='vertical_section',
            field=models.JSONField(
                null=True,
                blank=True,
                help_text="Vertical Section coordinate (meters)"
            ),
        ),
        migrations.AddField(
            model_name='calculatedsurvey',
            name='closure_distance',
            field=models.JSONField(
                null=True,
                blank=True,
                help_text="Closure Distance from first point (meters)"
            ),
        ),
        migrations.AddField(
            model_name='calculatedsurvey',
            name='closure_direction',
            field=models.JSONField(
                null=True,
                blank=True,
                help_text="Closure Direction from first point (degrees)"
            ),
        ),
        migrations.AddField(
            model_name='calculatedsurvey',
            name='vertical_section_azimuth',
            field=models.DecimalField(
                max_digits=6,
                decimal_places=2,
                null=True,
                blank=True,
                help_text="Azimuth for vertical section calculation (degrees)"
            ),
        ),
    ]
