# Generated by Django 5.2.7 on 2025-10-16 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0011_add_closure_vertical_section"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="surveyfile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Survey File",
                "verbose_name_plural": "Survey Files",
            },
        ),
        migrations.AddField(
            model_name="surveyfile",
            name="reference_for_survey",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary survey this is a reference for (if survey_role='reference')",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reference_surveys",
                to="survey_api.surveyfile",
            ),
        ),
        migrations.AddField(
            model_name="surveyfile",
            name="survey_role",
            field=models.CharField(
                choices=[
                    ("primary", "Primary Survey"),
                    ("reference", "Reference Survey"),
                    ("comparison", "Comparison Survey"),
                ],
                default="primary",
                help_text="Role of this survey: primary (actual), reference (planned/baseline), or comparison",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="surveyfile",
            index=models.Index(
                fields=["run", "survey_role"], name="idx_survey_files_run_role"
            ),
        ),
        migrations.AddIndex(
            model_name="surveyfile",
            index=models.Index(
                fields=["reference_for_survey"], name="idx_survey_files_ref_for"
            ),
        ),
    ]
