# Generated by Django 5.2.7 on 2025-10-19 05:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0012_add_survey_role_and_reference"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComparisonResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ratio_factor",
                    models.IntegerField(
                        default=10,
                        help_text="Scaling factor for visualization (1-100)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "md_data",
                    models.JSONField(help_text="Aligned MD stations (array of floats)"),
                ),
                (
                    "delta_x",
                    models.JSONField(
                        help_text="Easting deltas: ΔX = X_primary - X_reference (array of floats)"
                    ),
                ),
                (
                    "delta_y",
                    models.JSONField(
                        help_text="Northing deltas: ΔY = Y_primary - Y_reference (array of floats)"
                    ),
                ),
                (
                    "delta_z",
                    models.JSONField(
                        help_text="TVD deltas: ΔZ = TVD_primary - TVD_reference (array of floats)"
                    ),
                ),
                (
                    "delta_horizontal",
                    models.JSONField(
                        help_text="Horizontal displacement: √(ΔX² + ΔY²) (array of floats)"
                    ),
                ),
                (
                    "delta_total",
                    models.JSONField(
                        help_text="Total 3D displacement: √(ΔX² + ΔY² + ΔZ²) (array of floats)"
                    ),
                ),
                (
                    "delta_inc",
                    models.JSONField(
                        help_text="Inclination deltas: ΔInc = Inc_primary - Inc_reference (array of floats)"
                    ),
                ),
                (
                    "delta_azi",
                    models.JSONField(
                        help_text="Azimuth deltas with wraparound handling (array of floats)"
                    ),
                ),
                (
                    "statistics",
                    models.JSONField(
                        help_text="Statistical summary of deltas (max, avg, std, etc.)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this comparison",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_survey",
                    models.ForeignKey(
                        help_text="Primary (comparison) survey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons_as_primary",
                        to="survey_api.surveydata",
                    ),
                ),
                (
                    "reference_survey",
                    models.ForeignKey(
                        help_text="Reference (baseline) survey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons_as_reference",
                        to="survey_api.surveydata",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        help_text="Run that contains both surveys",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons",
                        to="survey_api.run",
                    ),
                ),
            ],
            options={
                "db_table": "comparison_results",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["run"], name="idx_comparison_run"),
                    models.Index(
                        fields=["primary_survey"], name="idx_comparison_primary"
                    ),
                    models.Index(
                        fields=["reference_survey"], name="idx_comparison_ref"
                    ),
                    models.Index(fields=["created_by"], name="idx_comparison_user"),
                ],
                "unique_together": {
                    ("primary_survey", "reference_survey", "ratio_factor")
                },
            },
        ),
    ]
