# Generated by Django 5.2.7 on 2025-10-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0013_comparisonresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="interpolatedsurvey",
            name="closure_direction_interpolated",
            field=models.JSONField(
                blank=True,
                help_text="Interpolated Closure Direction from first point (degrees)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="interpolatedsurvey",
            name="closure_distance_interpolated",
            field=models.JSONField(
                blank=True,
                help_text="Interpolated Closure Distance from first point (meters)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="interpolatedsurvey",
            name="vertical_section_interpolated",
            field=models.JSONField(
                blank=True,
                help_text="Interpolated Vertical Section (meters)",
                null=True,
            ),
        ),
    ]
