# Generated by Django 5.2.7 on 2025-10-19 08:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "survey_api",
            "0014_interpolatedsurvey_closure_direction_interpolated_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="latitude_degrees",
            field=models.IntegerField(
                blank=True,
                help_text="Latitude degrees component (-90 to 90)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="latitude_minutes",
            field=models.IntegerField(
                blank=True,
                help_text="Latitude minutes component (0 to 59)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(59),
                ],
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="latitude_seconds",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Latitude seconds component (0.0 to 59.999)",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("59.999")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="longitude_degrees",
            field=models.IntegerField(
                blank=True,
                help_text="Longitude degrees component (-180 to 180)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="longitude_minutes",
            field=models.IntegerField(
                blank=True,
                help_text="Longitude minutes component (0 to 59)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(59),
                ],
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="longitude_seconds",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Longitude seconds component (0.0 to 59.999)",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("59.999")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Latitude in decimal degrees (-90 to 90)",
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("-90.0")),
                    django.core.validators.MaxValueValidator(Decimal("90.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Longitude in decimal degrees (-180 to 180)",
                max_digits=11,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("-180.0")),
                    django.core.validators.MaxValueValidator(Decimal("180.0")),
                ],
            ),
        ),
    ]
