# Generated by Django 5.2.7 on 2025-10-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "survey_api",
            "0015_location_latitude_degrees_location_latitude_minutes_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="geodetic_datum",
            field=models.CharField(
                default="PSD 93",
                help_text="Geodetic datum (e.g., PSD 93, WGS84, NAD83)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="geodetic_system",
            field=models.CharField(
                default="Universal Transverse Mercator",
                help_text="Geodetic system (e.g., Universal Transverse Mercator)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="map_zone",
            field=models.CharField(
                default="Zone 40N(54E to 60E)",
                help_text="UTM zone or map zone identifier",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="north_reference",
            field=models.CharField(
                choices=[
                    ("True North", "True North"),
                    ("Grid North", "Grid North"),
                    ("Magnetic North", "Magnetic North"),
                ],
                default="Grid North",
                help_text="Reference north type",
                max_length=50,
            ),
        ),
    ]
