# Generated by Django 5.2.7 on 2025-10-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0016_location_geodetic_datum_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depth",
            name="elevation_reference",
            field=models.CharField(
                choices=[
                    ("KB", "Kelly Bushing"),
                    ("RT", "Rotary Table"),
                    ("GL", "Ground Level"),
                    ("MSL", "Mean Sea Level"),
                    ("DF", "Derrick Floor"),
                    ("RKB", "Rotary Kelly Bushing"),
                ],
                default="MSL",
                help_text="Elevation reference point (KB, RT, GL, MSL, etc.)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="depth",
            name="reference_datum",
            field=models.CharField(
                default="RKB/DFE(Drill Floor Elevation)",
                help_text="Reference datum (e.g., RKB/DFE, WGS84, NAVD88)",
                max_length=100,
            ),
        ),
    ]
