# Generated by Django 5.2.7 on 2025-10-19 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0017_alter_depth_elevation_reference_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HoleSectionMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hole_section_name",
                    models.CharField(
                        help_text='Hole section size (e.g., "12 1/4", "17 1/2")',
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("casing", "Casing"),
                            ("drill_pipe", "Drill Pipe"),
                            ("tubing", "Tubing"),
                        ],
                        help_text="Type of section: casing, drill_pipe, or tubing",
                        max_length=20,
                    ),
                ),
                (
                    "size_numeric",
                    models.DecimalField(
                        decimal_places=4,
                        help_text='Numeric representation for size comparison (e.g., 12.25 for "12 1/4")',
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hole Section Master",
                "verbose_name_plural": "Hole Section Masters",
                "db_table": "hole_section_master",
                "ordering": ["size_numeric"],
            },
        ),
        migrations.CreateModel(
            name="MinimumIdMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "minimum_id_name",
                    models.CharField(
                        help_text='Minimum ID value (e.g., "6.5", "8.835")',
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "size_numeric",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Numeric representation of the ID",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Minimum ID Master",
                "verbose_name_plural": "Minimum ID Masters",
                "db_table": "minimum_id_master",
                "ordering": ["size_numeric"],
            },
        ),
        migrations.CreateModel(
            name="SurveyRunInMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_in_name",
                    models.CharField(
                        help_text='Survey run-in value (e.g., "7\\" Casing", "4 1/2\\" Drillpipe")',
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "run_in_type",
                    models.CharField(
                        choices=[
                            ("casing", "Casing"),
                            ("drill_pipe", "Drill Pipe"),
                            ("tubing", "Tubing"),
                        ],
                        help_text="Type: casing, drill_pipe, or tubing",
                        max_length=20,
                    ),
                ),
                (
                    "size_numeric",
                    models.DecimalField(
                        decimal_places=4,
                        help_text='Numeric representation for size comparison (e.g., 7.0 for "7\\" Casing")',
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Survey Run-In Master",
                "verbose_name_plural": "Survey Run-In Masters",
                "db_table": "survey_run_in_master",
                "ordering": ["run_in_type", "size_numeric"],
            },
        ),
        migrations.AddField(
            model_name="tieon",
            name="survey_run_in_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("casing", "Casing"),
                    ("drill_pipe", "Drill Pipe"),
                    ("tubing", "Tubing"),
                ],
                help_text="Survey run-in type (casing or drill pipe)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tieon",
            name="hole_section_master",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected hole section from master data",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tieons",
                to="survey_api.holesectionmaster",
            ),
        ),
        migrations.AddField(
            model_name="tieon",
            name="minimum_id",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected minimum ID from master data",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tieons",
                to="survey_api.minimumidmaster",
            ),
        ),
        migrations.AddField(
            model_name="minimumidmaster",
            name="survey_run_in",
            field=models.ForeignKey(
                help_text="Associated survey run-in",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="minimum_ids",
                to="survey_api.surveyruninmaster",
            ),
        ),
        migrations.AddField(
            model_name="tieon",
            name="survey_run_in",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected survey run-in from master data",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tieons",
                to="survey_api.surveyruninmaster",
            ),
        ),
    ]
