# Generated by Django 5.2.7 on 2025-10-19 10:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "survey_api",
            "0018_holesectionmaster_minimumidmaster_surveyruninmaster_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tieon",
            name="expected_inclination",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Expected inclination (<=5° = Vertical, >5° = Deviated)",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("180.00")),
                ],
            ),
        ),
    ]
