# Generated by Django 5.2.7 on 2025-10-19 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0019_tieon_expected_inclination"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tieon",
            name="hole_section",
        ),
        migrations.RemoveField(
            model_name="tieon",
            name="survey_tool_type",
        ),
    ]
