# Generated by Django 5.2.7 on 2025-10-19 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0020_remove_tieon_hole_section_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tieon",
            name="casing_selected",
        ),
        migrations.RemoveField(
            model_name="tieon",
            name="drillpipe_selected",
        ),
    ]
