# Generated by Django 5.2.7 on 2025-10-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0021_remove_tieon_casing_selected_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comparisonresult",
            name="comparison_azi",
            field=models.JSONField(
                blank=True,
                help_text="Comparison survey azimuth values (array of floats)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="comparisonresult",
            name="comparison_easting",
            field=models.JSONField(
                blank=True,
                help_text="Comparison survey easting coordinates (array of floats)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="comparisonresult",
            name="comparison_inc",
            field=models.JSONField(
                blank=True,
                help_text="Comparison survey inclination values (array of floats)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="comparisonresult",
            name="comparison_northing",
            field=models.JSONField(
                blank=True,
                help_text="Comparison survey northing coordinates (array of floats)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="comparisonresult",
            name="comparison_tvd",
            field=models.JSONField(
                blank=True,
                help_text="Comparison survey TVD values (array of floats)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="comparisonresult",
            name="reference_azi",
            field=models.JSONField(
                blank=True,
                help_text="Reference survey azimuth values (array of floats)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="comparisonresult",
            name="reference_easting",
            field=models.JSONField(
                blank=True,
                help_text="Reference survey easting coordinates (array of floats)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="comparisonresult",
            name="reference_inc",
            field=models.JSONField(
                blank=True,
                help_text="Reference survey inclination values (array of floats)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="comparisonresult",
            name="reference_northing",
            field=models.JSONField(
                blank=True,
                help_text="Reference survey northing coordinates (array of floats)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="comparisonresult",
            name="reference_tvd",
            field=models.JSONField(
                blank=True,
                help_text="Reference survey TVD values (array of floats)",
                null=True,
            ),
        ),
    ]
