# Generated by Django 5.2.7 on 2025-10-20 05:35

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0022_add_survey_coordinates_to_comparison"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comparisonresult",
            name="ratio_factor",
            field=models.IntegerField(
                default=5,
                help_text="Interpolation step size in meters (default: 5m)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.CreateModel(
            name="CurveAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "md_start",
                    models.FloatField(
                        help_text="Starting measured depth for offset application"
                    ),
                ),
                (
                    "md_end",
                    models.FloatField(
                        help_text="Ending measured depth for offset application"
                    ),
                ),
                (
                    "x_offset",
                    models.FloatField(
                        default=0.0, help_text="Easting (X) offset in meters"
                    ),
                ),
                (
                    "y_offset",
                    models.FloatField(
                        default=0.0, help_text="Northing (Y) offset in meters"
                    ),
                ),
                (
                    "z_offset",
                    models.FloatField(
                        default=0.0, help_text="TVD (Z) offset in meters"
                    ),
                ),
                (
                    "md_data",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        help_text="Measured depth array",
                        size=None,
                    ),
                ),
                (
                    "north_adjusted",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        help_text="Adjusted northing coordinates",
                        size=None,
                    ),
                ),
                (
                    "east_adjusted",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        help_text="Adjusted easting coordinates",
                        size=None,
                    ),
                ),
                (
                    "tvd_adjusted",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        help_text="Adjusted TVD coordinates",
                        size=None,
                    ),
                ),
                (
                    "inc_recalculated",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        blank=True,
                        help_text="Recalculated inclination from adjusted path",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "azi_recalculated",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        blank=True,
                        help_text="Recalculated azimuth from adjusted path",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "adjustment_sequence",
                    models.IntegerField(
                        default=0, help_text="Sequence number for undo/redo operations"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the current active adjustment",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comparison",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="survey_api.comparisonresult",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "curve_adjustments",
                "ordering": ["adjustment_sequence"],
                "indexes": [
                    models.Index(
                        fields=["comparison", "is_current"],
                        name="curve_adjus_compari_ea7b86_idx",
                    ),
                    models.Index(
                        fields=["comparison", "adjustment_sequence"],
                        name="curve_adjus_compari_056703_idx",
                    ),
                ],
            },
        ),
    ]
