# Generated by Django 5.2.7 on 2025-10-21 06:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0023_alter_comparisonresult_ratio_factor_curveadjustment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Extrapolation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "extrapolation_length",
                    models.FloatField(
                        help_text="How far to extrapolate beyond last point (meters)"
                    ),
                ),
                (
                    "extrapolation_step",
                    models.FloatField(
                        help_text="Distance between extrapolated points (meters)"
                    ),
                ),
                (
                    "interpolation_step",
                    models.FloatField(
                        help_text="Distance between interpolated points (meters)"
                    ),
                ),
                (
                    "extrapolation_method",
                    models.CharField(
                        choices=[
                            ("Constant", "Constant - Use last values"),
                            ("Linear Trend", "Linear Trend - Follow trend"),
                            ("Curve Fit", "Curve Fit - Polynomial fitting"),
                        ],
                        default="Constant",
                        max_length=20,
                    ),
                ),
                ("original_md", models.JSONField(help_text="Original measured depths")),
                ("original_inc", models.JSONField(help_text="Original inclinations")),
                ("original_azi", models.JSONField(help_text="Original azimuths")),
                (
                    "original_north",
                    models.JSONField(help_text="Original northing coordinates"),
                ),
                (
                    "original_east",
                    models.JSONField(help_text="Original easting coordinates"),
                ),
                ("original_tvd", models.JSONField(help_text="Original TVD")),
                (
                    "interpolated_md",
                    models.JSONField(help_text="Interpolated measured depths"),
                ),
                (
                    "interpolated_inc",
                    models.JSONField(help_text="Interpolated inclinations"),
                ),
                (
                    "interpolated_azi",
                    models.JSONField(help_text="Interpolated azimuths"),
                ),
                (
                    "interpolated_north",
                    models.JSONField(help_text="Interpolated northing coordinates"),
                ),
                (
                    "interpolated_east",
                    models.JSONField(help_text="Interpolated easting coordinates"),
                ),
                ("interpolated_tvd", models.JSONField(help_text="Interpolated TVD")),
                (
                    "extrapolated_md",
                    models.JSONField(help_text="Extrapolated measured depths"),
                ),
                (
                    "extrapolated_inc",
                    models.JSONField(help_text="Extrapolated inclinations"),
                ),
                (
                    "extrapolated_azi",
                    models.JSONField(help_text="Extrapolated azimuths"),
                ),
                (
                    "extrapolated_north",
                    models.JSONField(help_text="Extrapolated northing coordinates"),
                ),
                (
                    "extrapolated_east",
                    models.JSONField(help_text="Extrapolated easting coordinates"),
                ),
                ("extrapolated_tvd", models.JSONField(help_text="Extrapolated TVD")),
                ("combined_md", models.JSONField(help_text="Combined measured depths")),
                ("combined_inc", models.JSONField(help_text="Combined inclinations")),
                ("combined_azi", models.JSONField(help_text="Combined azimuths")),
                (
                    "combined_north",
                    models.JSONField(help_text="Combined northing coordinates"),
                ),
                (
                    "combined_east",
                    models.JSONField(help_text="Combined easting coordinates"),
                ),
                ("combined_tvd", models.JSONField(help_text="Combined TVD")),
                ("original_point_count", models.IntegerField(default=0)),
                ("interpolated_point_count", models.IntegerField(default=0)),
                ("extrapolated_point_count", models.IntegerField(default=0)),
                ("final_md", models.FloatField(blank=True, null=True)),
                ("final_tvd", models.FloatField(blank=True, null=True)),
                (
                    "final_horizontal_displacement",
                    models.FloatField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extrapolations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        help_text="Run this extrapolation belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extrapolations",
                        to="survey_api.run",
                    ),
                ),
                (
                    "survey_data",
                    models.ForeignKey(
                        help_text="Original survey data that was extrapolated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extrapolations",
                        to="survey_api.surveydata",
                    ),
                ),
            ],
            options={
                "db_table": "extrapolations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["survey_data"], name="extrapolati_survey__35bec5_idx"
                    ),
                    models.Index(fields=["run"], name="extrapolati_run_id_5ebf5d_idx"),
                    models.Index(
                        fields=["created_at"], name="extrapolati_created_e4cad3_idx"
                    ),
                ],
            },
        ),
    ]
