# Generated by Django 5.2.7 on 2025-10-21 08:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0024_extrapolation"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("run_created", "Run Created"),
                            ("run_updated", "Run Updated"),
                            ("run_deleted", "Run Deleted"),
                            ("survey_uploaded", "Survey Uploaded"),
                            ("survey_deleted", "Survey Deleted"),
                            ("survey_calculated", "Survey Calculated"),
                            ("survey_interpolated", "Survey Interpolated"),
                            ("survey_viewed", "Survey Viewed"),
                            ("comparison_created", "Comparison Created"),
                            ("comparison_viewed", "Comparison Viewed"),
                            ("comparison_deleted", "Comparison Deleted"),
                            ("comparison_exported", "Comparison Exported"),
                            ("adjustment_applied", "Adjustment Applied"),
                            ("adjustment_reset", "Adjustment Reset"),
                            ("adjustment_undone", "Adjustment Undone"),
                            ("adjustment_redone", "Adjustment Redone"),
                            ("extrapolation_calculated", "Extrapolation Calculated"),
                            ("extrapolation_saved", "Extrapolation Saved"),
                            ("extrapolation_deleted", "Extrapolation Deleted"),
                            (
                                "duplicate_survey_calculated",
                                "Duplicate Survey Calculated",
                            ),
                            ("duplicate_survey_exported", "Duplicate Survey Exported"),
                            ("reference_survey_uploaded", "Reference Survey Uploaded"),
                            ("reference_survey_deleted", "Reference Survey Deleted"),
                            ("tieon_created", "Tie-on Created"),
                            ("tieon_updated", "Tie-on Updated"),
                            ("tieon_deleted", "Tie-on Deleted"),
                            ("data_exported", "Data Exported"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="survey_api.run",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="run_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "run_activity_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["run", "-created_at"],
                        name="run_activit_run_id_c6a34c_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="run_activit_user_id_4ae209_idx",
                    ),
                    models.Index(
                        fields=["activity_type", "-created_at"],
                        name="run_activit_activit_05a529_idx",
                    ),
                ],
            },
        ),
    ]
