# Generated by Django 5.2.7 on 2025-10-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0025_runactivitylog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="well",
            name="well_type",
        ),
        migrations.AddField(
            model_name="well",
            name="well_id",
            field=models.CharField(
                blank=True,
                help_text="Unique well identifier",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
