# Generated by Django 5.2.7 on 2025-10-26 06:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0026_remove_well_well_type_well_well_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tieon",
            name="is_bhc",
            field=models.BooleanField(
                default=False,
                help_text="Bottom Hole Convergence flag - when enabled, proposal_direction is automatically set to 0",
            ),
        ),
        migrations.AddField(
            model_name="tieon",
            name="proposal_direction",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Proposal direction (0-360 degrees) - auto-set to 0 when BHC is enabled",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("360.00")),
                ],
            ),
        ),
    ]
