# Generated by Django 5.2.7 on 2025-10-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0027_tieon_is_bhc_tieon_proposal_direction"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="min_g_t",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Minimum grid convergence (calculated)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="min_w_t",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Minimum scale factor (calculated)",
                max_digits=12,
                null=True,
            ),
        ),
    ]
