# Generated by Django 5.2.7 on 2025-10-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0028_location_min_g_t_location_min_w_t"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="survey_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Type 1 - GTL", "Type 1 - GTL"),
                    ("Type 2 - Gyro", "Type 2 - Gyro"),
                    ("Type 3 - MWD", "Type 3 - MWD"),
                    ("Type 4 - Unknown", "Type 4 - Unknown"),
                ],
                help_text="Survey type - optional, can be determined from uploaded file",
                max_length=50,
                null=True,
            ),
        ),
    ]
