# Generated by Django 5.1.5 on 2025-10-27 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0030_qualitycheck"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualitycheck",
            name="survey_data",
            field=models.OneToOneField(
                blank=True,
                help_text="Link to approved SurveyData (set after QA approval)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quality_check",
                to="survey_api.surveydata",
            ),
        ),
    ]
