# Generated by Django 5.2.7 on 2025-10-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0031_add_survey_data_to_quality_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualitycheck",
            name="delta_gt_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Delta G(t) percentage (0-100) - saved after approval",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="qualitycheck",
            name="delta_gt_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Delta G(t) score (normalized 0-1) - saved after approval",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="qualitycheck",
            name="delta_wt_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Delta W(t) percentage (0-100) - saved after approval",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="qualitycheck",
            name="delta_wt_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Delta W(t) score (normalized 0-1) - saved after approval",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="qualitycheck",
            name="g_t_score_points",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total G(t) score points earned - saved after approval",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="qualitycheck",
            name="max_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum possible score (total_rows × 1.5) - saved after approval",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="qualitycheck",
            name="total_rows",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of rows in the survey - saved after approval",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="qualitycheck",
            name="w_t_score_points",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total W(t) score points earned - saved after approval",
                max_digits=10,
                null=True,
            ),
        ),
    ]
