# Generated by Django 5.2.7 on 2025-10-29 07:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0033_rename_run_type_to_survey_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "client_name",
                    models.CharField(help_text="Client name", max_length=255),
                ),
                (
                    "client_code",
                    models.CharField(
                        blank=True,
                        help_text="Unique client code (optional)",
                        max_length=50,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Client code must contain only uppercase letters, numbers, hyphens, and underscores",
                                regex="^[A-Z0-9_-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Primary contact email",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Primary contact phone number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        help_text="Contact person name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this client is active"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the client",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "clients",
                "ordering": ["client_name"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        help_text="Unique customer name", max_length=255, unique=True
                    ),
                ),
                (
                    "customer_code",
                    models.CharField(
                        blank=True,
                        help_text="Unique customer code (optional)",
                        max_length=50,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Customer code must contain only uppercase letters, numbers, hyphens, and underscores",
                                regex="^[A-Z0-9_-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Primary contact email",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Primary contact phone number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Customer address", null=True
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, help_text="Country", max_length=100, null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this customer is active"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the customer",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "customers",
                "ordering": ["customer_name"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_number",
                    models.CharField(
                        help_text="Unique job identifier/number",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "job_name",
                    models.CharField(help_text="Descriptive job name", max_length=255),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, help_text="Job start date", null=True),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, help_text="Job end date", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("on_hold", "On Hold"),
                        ],
                        default="planned",
                        help_text="Current job status",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Job description", null=True
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="External reference number (PO, AFE, etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "db_table": "jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Rig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rig_name", models.CharField(help_text="Rig name", max_length=255)),
                (
                    "rig_number",
                    models.CharField(
                        help_text="Unique rig number/identifier",
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Rig number must contain only uppercase letters, numbers, hyphens, and underscores",
                                regex="^[A-Z0-9_-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "rig_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Land", "Land Rig"),
                            ("Jack-up", "Jack-up Rig"),
                            ("Semi-submersible", "Semi-submersible"),
                            ("Drillship", "Drillship"),
                            ("Platform", "Platform Rig"),
                            ("Other", "Other"),
                        ],
                        help_text="Type of rig",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "contractor",
                    models.CharField(
                        blank=True,
                        help_text="Rig contractor/operator",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        blank=True, help_text="Rig owner", max_length=255, null=True
                    ),
                ),
                (
                    "capacity",
                    models.CharField(
                        blank=True,
                        help_text="Rig drilling capacity (e.g., 30,000 ft)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "build_year",
                    models.IntegerField(
                        blank=True, help_text="Year rig was built", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this rig is active"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the rig",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rigs",
                "ordering": ["rig_name"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        help_text="Service name", max_length=255, unique=True
                    ),
                ),
                (
                    "service_code",
                    models.CharField(
                        blank=True,
                        help_text="Unique service code (optional)",
                        max_length=50,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Service code must contain only uppercase letters, numbers, hyphens, and underscores",
                                regex="^[A-Z0-9_-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Service description", null=True
                    ),
                ),
                (
                    "service_category",
                    models.CharField(
                        blank=True,
                        help_text="Service category (e.g., Directional Drilling, MWD, Gyro)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this service is active"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the service",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "services",
                "ordering": ["service_name"],
            },
        ),
        migrations.AlterModelOptions(
            name="well",
            options={
                "ordering": ["well_name"],
                "verbose_name": "Well",
                "verbose_name_plural": "Wells",
            },
        ),
        migrations.AddField(
            model_name="well",
            name="completion_date",
            field=models.DateField(
                blank=True, help_text="Date well was completed", null=True
            ),
        ),
        migrations.AddField(
            model_name="well",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_wells",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="well",
            name="field_name",
            field=models.CharField(
                blank=True, help_text="Oil/gas field name", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="well",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this well is active"
            ),
        ),
        migrations.AddField(
            model_name="well",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Additional notes about the well", null=True
            ),
        ),
        migrations.AddField(
            model_name="well",
            name="operator",
            field=models.CharField(
                blank=True, help_text="Well operator company", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="well",
            name="spud_date",
            field=models.DateField(
                blank=True, help_text="Date drilling commenced", null=True
            ),
        ),
        migrations.AddField(
            model_name="well",
            name="status",
            field=models.CharField(
                choices=[
                    ("Planning", "Planning"),
                    ("Drilling", "Drilling"),
                    ("Completed", "Completed"),
                    ("Producing", "Producing"),
                    ("Suspended", "Suspended"),
                    ("Abandoned", "Abandoned"),
                ],
                default="Planning",
                help_text="Current well status",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="well",
            name="total_depth",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total depth of well (meters)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="well",
            name="well_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Oil", "Oil Well"),
                    ("Gas", "Gas Well"),
                    ("Water Injection", "Water Injection"),
                    ("Gas Injection", "Gas Injection"),
                    ("Exploration", "Exploration"),
                    ("Development", "Development"),
                    ("Appraisal", "Appraisal"),
                    ("Other", "Other"),
                ],
                help_text="Type of well",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="well",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="runs_direct",
                to="survey_api.well",
            ),
        ),
        migrations.AlterField(
            model_name="well",
            name="well_id",
            field=models.CharField(
                help_text="Official well identifier/API number",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="well",
            name="well_name",
            field=models.CharField(
                help_text="Unique well name", max_length=255, unique=True
            ),
        ),
        migrations.AddIndex(
            model_name="well",
            index=models.Index(fields=["well_name"], name="idx_wells_name"),
        ),
        migrations.AddIndex(
            model_name="well",
            index=models.Index(fields=["well_id"], name="idx_wells_well_id"),
        ),
        migrations.AddIndex(
            model_name="well",
            index=models.Index(fields=["field_name"], name="idx_wells_field"),
        ),
        migrations.AddIndex(
            model_name="well",
            index=models.Index(fields=["status"], name="idx_wells_status"),
        ),
        migrations.AddIndex(
            model_name="well",
            index=models.Index(fields=["is_active"], name="idx_wells_active"),
        ),
        migrations.AddField(
            model_name="client",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_clients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_customers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="customer",
            field=models.ForeignKey(
                help_text="Customer this client belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="survey_api.customer",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="client",
            field=models.ForeignKey(
                help_text="Client for this job",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="survey_api.client",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="customer",
            field=models.ForeignKey(
                help_text="Customer for this job",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="survey_api.customer",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="well",
            field=models.ForeignKey(
                help_text="Well for this job",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="survey_api.well",
            ),
        ),
        migrations.AddField(
            model_name="run",
            name="job",
            field=models.ForeignKey(
                blank=True,
                help_text="Job this run belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to="survey_api.job",
            ),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["job"], name="idx_runs_job_id"),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["survey_type"], name="idx_runs_survey_type"),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["user"], name="idx_runs_user_id"),
        ),
        migrations.AddField(
            model_name="rig",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_rigs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="rig",
            field=models.ForeignKey(
                help_text="Rig for this job",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="survey_api.rig",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_services",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="service",
            field=models.ForeignKey(
                help_text="Service for this job",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="survey_api.service",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["customer_name"], name="idx_customers_name"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["customer_code"], name="idx_customers_code"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["is_active"], name="idx_customers_active"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["customer"], name="idx_clients_customer"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["client_name"], name="idx_clients_name"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["client_code"], name="idx_clients_code"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["is_active"], name="idx_clients_active"),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                fields=("customer", "client_name"),
                name="unique_client_name_per_customer",
            ),
        ),
        migrations.AddIndex(
            model_name="rig",
            index=models.Index(fields=["rig_name"], name="idx_rigs_name"),
        ),
        migrations.AddIndex(
            model_name="rig",
            index=models.Index(fields=["rig_number"], name="idx_rigs_number"),
        ),
        migrations.AddIndex(
            model_name="rig",
            index=models.Index(fields=["rig_type"], name="idx_rigs_type"),
        ),
        migrations.AddIndex(
            model_name="rig",
            index=models.Index(fields=["is_active"], name="idx_rigs_active"),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["service_name"], name="idx_services_name"),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["service_code"], name="idx_services_code"),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["service_category"], name="idx_services_category"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["is_active"], name="idx_services_active"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["job_number"], name="idx_jobs_job_number"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["customer"], name="idx_jobs_customer_id"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["client"], name="idx_jobs_client_id"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["well"], name="idx_jobs_well_id"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["rig"], name="idx_jobs_rig_id"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["service"], name="idx_jobs_service_id"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["status"], name="idx_jobs_status"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["start_date"], name="idx_jobs_start_date"),
        ),
    ]
