# Generated by Django 5.2.7 on 2025-10-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0034_create_master_data_and_job_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="job_name",
        ),
        migrations.RemoveField(
            model_name="job",
            name="reference_number",
        ),
        migrations.AlterField(
            model_name="job",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Auto-populated from last run upload date",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_number",
            field=models.CharField(
                editable=False,
                help_text="Auto-generated unique job identifier (e.g., OM1001)",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="start_date",
            field=models.DateField(
                blank=True,
                help_text="Auto-populated from first run upload date",
                null=True,
            ),
        ),
    ]
