# Generated by Django 5.2.7 on 2025-10-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0036_simplify_master_data_models"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="client",
            name="unique_client_name_per_customer",
        ),
        migrations.RemoveIndex(
            model_name="client",
            name="idx_clients_customer",
        ),
        migrations.RemoveField(
            model_name="client",
            name="customer",
        ),
        migrations.AlterField(
            model_name="client",
            name="client_name",
            field=models.CharField(
                help_text="Client name", max_length=255, unique=True
            ),
        ),
    ]
