# Generated by Django 5.2.7 on 2025-10-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0038_update_rig_model_add_rig_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rig",
            name="rig_number",
            field=models.CharField(
                help_text="Unique rig number", max_length=100, unique=True
            ),
        ),
    ]
