# Generated by Django 5.2.7 on 2025-10-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0039_alter_rig_rig_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="run_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="run",
            name="run_number",
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="run",
            constraint=models.UniqueConstraint(
                fields=("job", "run_number"), name="unique_run_number_per_job"
            ),
        ),
        migrations.AddConstraint(
            model_name="run",
            constraint=models.UniqueConstraint(
                fields=("job", "run_name"), name="unique_run_name_per_job"
            ),
        ),
    ]
