# Generated by Django 5.2.7 on 2025-10-29 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0040_alter_run_run_name_alter_run_run_number_and_more"),
    ]

    operations = [
        # Remove the old global unique constraint on run_number
        migrations.RunSQL(
            sql='ALTER TABLE runs DROP CONSTRAINT IF EXISTS runs_run_number_key;',
            reverse_sql='ALTER TABLE runs ADD CONSTRAINT runs_run_number_key UNIQUE (run_number);'
        ),
        # Remove the old global unique constraint on run_name
        migrations.RunSQL(
            sql='ALTER TABLE runs DROP CONSTRAINT IF EXISTS runs_run_name_key;',
            reverse_sql='ALTER TABLE runs ADD CONSTRAINT runs_run_name_key UNIQUE (run_name);'
        ),
    ]
