# Generated by Django 5.2.7 on 2026-01-08 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0041_remove_old_run_unique_constraints"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="minimumidmaster",
            options={"ordering": ["size_numeric"]},
        ),
        migrations.AlterField(
            model_name="minimumidmaster",
            name="minimum_id_name",
            field=models.CharField(
                help_text='Minimum ID value (e.g., "6.000")', max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="minimumidmaster",
            name="size_numeric",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name="minimumidmaster",
            name="survey_run_in",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="minimum_ids",
                to="survey_api.surveyruninmaster",
            ),
        ),
        migrations.AddConstraint(
            model_name="minimumidmaster",
            constraint=models.UniqueConstraint(
                fields=("minimum_id_name", "survey_run_in"), name="unique_id_per_runin"
            ),
        ),
    ]
